// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-RBm6mApkEbQR232XDwy6VDvzvWi_Tnw',
    appId: '1:882444292027:web:45bb35200a8907785fbe9e',
    messagingSenderId: '882444292027',
    projectId: 'mypr-c005b',
    authDomain: 'mypr-c005b.firebaseapp.com',
    storageBucket: 'mypr-c005b.firebasestorage.app',
    measurementId: 'G-8J0RFXF98P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu1XSV4yU3tMDdrmpkipurypKAPHLMO1o',
    appId: '1:882444292027:android:02e6aad26e35cb3e5fbe9e',
    messagingSenderId: '882444292027',
    projectId: 'mypr-c005b',
    storageBucket: 'mypr-c005b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-KdZOzYrSVRXbxDAhlyt4PGru9WtaDuQ',
    appId: '1:882444292027:ios:5e0851dc0c993dda5fbe9e',
    messagingSenderId: '882444292027',
    projectId: 'mypr-c005b',
    storageBucket: 'mypr-c005b.firebasestorage.app',
    iosBundleId: 'com.example.mypr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-KdZOzYrSVRXbxDAhlyt4PGru9WtaDuQ',
    appId: '1:882444292027:ios:5e0851dc0c993dda5fbe9e',
    messagingSenderId: '882444292027',
    projectId: 'mypr-c005b',
    storageBucket: 'mypr-c005b.firebasestorage.app',
    iosBundleId: 'com.example.mypr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-RBm6mApkEbQR232XDwy6VDvzvWi_Tnw',
    appId: '1:882444292027:web:4bcaf70bde81d8f35fbe9e',
    messagingSenderId: '882444292027',
    projectId: 'mypr-c005b',
    authDomain: 'mypr-c005b.firebaseapp.com',
    storageBucket: 'mypr-c005b.firebasestorage.app',
    measurementId: 'G-J05DQN2NP0',
  );
}
